import type { Metadata } from "next";
import { Geist } from "next/font/google";

import "./globals.css";
import { Providers } from "@/app/providers";
import Header from "@/app/components/header/header";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Reem Portfolio",
  description: "Generated by create next app",
  icons: {
    icon: '/globe.svg',
    shortcut: '/globe.svg',
    apple: '/globe.svg',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} antialiased`}
      >
        <Providers>
         <Header/>
        {children}
        </Providers>
      </body>
    </html>
  );
}
